### ISSUE TITLE
Test suite description file comprehension

### ISSUE THREAD

**Issue by k0pernicus** [JonHylands/fxos-powertool#14]
Hi!
I don't understand the need to use the test suite description file. Is this file a "scenario" to elaborate some tests? If it's ok, is this tool will execute this scenario and measure the electric consummation per test?
Also, is this tool is compatible to run with an Android smartphone, or is it just for the specific FirefoxOS platform?

Thanks a lot!

**Comment by JonHylands** [comment]
The descriptor is basically just telling the software how many tests are to be run, and what each test's name is. You don't need a descriptor file if you're just doing ad-hoc testing.

The software side of the tool is phone-agnostic, but the battery harness that fits inside a phone and connects to the ammeter hardware is phone-specific.

**Comment by k0pernicus** [comment]
Great! Thank you very much :-)
